/*
  2026 Shambhala set times used by this fan-made schedule page.
  Source: official downloadable schedule, accessed July 1, 2026.
  Check the official festival schedule/app for changes.
*/
window.SCHEDULE_DATA = {
  "Thursday": {
    "amp": [
      ["12:00 PM", "VCTRE"],
      ["1:00 PM", "BOYNOTHOME"],
      ["2:00 PM", "S2"],
      ["3:00 PM", "TWO GIRLS ONE LAPTOP"],
      ["4:00 PM", "SKIITOUR"],
      ["5:30 PM", "AHEE"],
      ["6:30 PM", "AMP LIVE"],
      ["7:30 PM", "COMISAR"],
      ["8:30 PM", "DEFIED"],
      ["9:00 PM", "RICHARD FINGER"],
      ["10:00 PM", "EAZYBAKED"],
      ["11:00 PM", "WICKED LESTER"],
      ["12:00 AM", "CRAZE"],
      ["1:00 AM", "LONGWALKSHORTDOCK"]
    ],
    "living-room": [
      ["12:00 PM", "JAQ & SASAKI"],
      ["1:00 PM", "HOOLA"],
      ["2:30 PM", "HA HA"],
      ["3:30 PM", "BITCHIN'"],
      ["5:00 PM", "FOXY MORON"],
      ["6:30 PM", "FLIPOUT & JUNK"],
      ["8:00 PM", "SONREAL"],
      ["9:30 PM", "SHAWNA (KMLN)"],
      ["11:00 PM", "GALEN"],
      ["12:30 AM", "PHIL HARTNOLL (ORBITAL)"]
    ],
    "pagoda": [
      ["12:00 PM", "RBR TAKEOVER: CHRIS CORKAL"],
      ["1:00 PM", "EDWARD LANE"],
      ["2:00 PM", "KÖL"],
      ["3:00 PM", "CERDIN"],
      ["4:00 PM", "LAW"],
      ["5:00 PM", "AVERAGE CITIZENS"],
      ["6:15 PM", "PRAYER HANDZ"],
      ["7:30 PM", "CASE OF THE MONDAYS"],
      ["8:30 PM", "BEN FOX"],
      ["9:30 PM", "N2N"],
      ["10:45 PM", "SOUP"],
      ["12:00 AM", "JON CASEY"],
      ["1:15 AM", "CRANKDAT"]
    ]
  },
  "Friday": {
    "amp": [
      ["5:00 PM", "ASÁU"],
      ["6:00 PM", "AIR CASTLES"],
      ["7:00 PM", "MANTRA SOUNDS"],
      ["8:00 PM", "VEIL"],
      ["9:00 PM", "FLAVA D"],
      ["10:00 PM", "NIKITA, THE WICKED"],
      ["11:00 PM", "PEEKABOO"],
      ["12:00 AM", "RUSKO"],
      ["1:30 AM", "TRUTH W/ PAV4N"],
      ["2:45 AM", "SIMULA W/ JAKES (140 SET)"]
    ],
    "fractal-forest": [
      ["4:30 PM", "FREDDY J"],
      ["6:00 PM", "SIVZ"],
      ["7:00 PM", "BURCHILL"],
      ["8:00 PM", "KIINJO"],
      ["9:00 PM", "VINCENT ANTONE"],
      ["10:00 PM", "STICKYBUDS"],
      ["11:00 PM", "Z-TRIP"],
      ["12:00 AM", "CHALI 2NA & CUT CHEMIST"],
      ["1:00 AM", "THE FUNK HUNTERS"],
      ["2:00 AM", "SMALLTOWN DJS"],
      ["3:00 AM", "CONTROL ROOM"],
      ["4:00 AM", "JOANNA MAGIK"],
      ["5:00 AM", "JOSEPH MARTIN"]
    ],
    "grove": [
      ["1:30 PM", "LAZY SYRUP ORCHESTRA"],
      ["3:00 PM", "HANDSOME TIGER"],
      ["4:00 PM", "OKIRO"],
      ["5:00 PM", "MFINITY"],
      ["6:00 PM", "BIISHOP"],
      ["7:00 PM", "COLTCUTS"],
      ["8:00 PM", "PONDA"],
      ["8:45 PM", "MAGUGU"],
      ["9:45 PM", "SIR SPYRO"],
      ["11:15 PM", "SACRED G'S"],
      ["11:30 PM", "MAIN PHASE"],
      ["1:00 AM", "INTERPLANETARY CRIMINAL"],
      ["2:30 AM", "MADAM X"],
      ["4:00 AM", "SHINY THINGS"],
      ["5:00 AM", "SUNDOG"]
    ],
    "living-room": [
      ["12:00 PM", "QDUP"],
      ["1:00 PM", "ALL GOOD FUNK ALLIANCE"],
      ["2:00 PM", "FORT KNOX 5"],
      ["3:00 PM", "NATURALIST"],
      ["4:00 PM", "MEOWMIX"],
      ["5:30 PM", "MOONTRICKS"],
      ["7:00 PM", "KR3TURE"],
      ["8:15 PM", "EVERYMAN"],
      ["8:30 PM", "SUPER DJ DMITRY (DEEE-LITE)"],
      ["10:00 PM", "SOUL CLAP"],
      ["12:00 AM", "DANCE FOR DAN (DJ DAN TRIBUTE)"],
      ["1:00 AM", "DOC MARTIN"],
      ["3:00 AM", "DAMIAN LAZARUS"]
    ],
    "pagoda": [
      ["3:00 PM", "LOGAN HART"],
      ["4:00 PM", "ANGIE C"],
      ["5:00 PM", "LAAV"],
      ["6:00 PM", "JOLUCA"],
      ["7:15 PM", "TCHILT"],
      ["8:15 PM", "TCHILT B2B MNTRA"],
      ["8:30 PM", "MNTRA"],
      ["9:30 PM", "JUSTIN MARTIN"],
      ["11:15 PM", "LOUIS THE CHILD"],
      ["12:30 AM", "SIDEPIECE"],
      ["2:00 AM", "DR. FRESCH"],
      ["4:00 AM", "NO THANKS"],
      ["5:00 AM", "STUND"]
    ],
    "village": [
      ["3:00 PM", "VILLAGE RINSEOUT HOSTED BY JOHN ROLODEX"],
      ["8:30 PM", "ARMANNI REIGN"],
      ["9:00 PM", "STYLUST"],
      ["10:00 PM", "SUBVERT"],
      ["11:00 PM", "TVBOO"],
      ["12:30 AM", "EXCISION"],
      ["2:00 AM", "GRAFIX"],
      ["3:00 AM", "SUBSONIC"],
      ["4:15 AM", "BUDDY & THE BUFFALO"]
    ]
  },
  "Saturday": {
    "amp": [
      ["4:30 PM", "ATEBAKI"],
      ["5:30 PM", "SEEDED VISION"],
      ["6:30 PM", "TORBJØRN"],
      ["7:30 PM", "KYBER"],
      ["8:30 PM", "LUMASI"],
      ["9:30 PM", "KNOW GOOD"],
      ["11:00 PM", "INZO"],
      ["12:30 AM", "LIQUID STRANGER"],
      ["1:30 AM", "WHETHAN"],
      ["2:45 AM", "JKYL & HYDE"]
    ],
    "fractal-forest": [
      ["4:00 PM", "JGIRL & MANOUSOS"],
      ["5:00 PM", "DEEPSTRUT"],
      ["6:00 PM", "FATTYCAKES"],
      ["7:00 PM", "CHARLY HUSTLE"],
      ["8:00 PM", "THE GAFF"],
      ["9:00 PM", "STARJUNK 95"],
      ["10:00 PM", "CHROMEO DJ SET"],
      ["11:00 PM", "A-TRAK"],
      ["12:00 AM", "SOLARDO"],
      ["1:00 AM", "NEON STEVE"],
      ["2:00 AM", "A.SKILLZ"],
      ["3:00 AM", "FORT KNOX 5 & QDUP"],
      ["4:00 AM", "SLYNK"],
      ["5:00 AM", "NEIGHBOUR"]
    ],
    "grove": [
      ["2:30 PM", "EL TORO"],
      ["3:30 PM", "TOO MANY ZOOZ"],
      ["4:45 PM", "MARK WOODYARD"],
      ["6:00 PM", "ALL:LO COLLECTIVE: ALEX UNGER"],
      ["6:45 PM", "PHEEL."],
      ["7:30 PM", "PARKBREEZY"],
      ["8:15 PM", "TF MARZ"],
      ["9:00 PM", "PRSN"],
      ["10:00 PM", "EARTHGANG"],
      ["10:45 PM", "CONDUCTA B2B DJ SWISHA"],
      ["12:45 AM", "IVY LAB"],
      ["2:00 AM", "V.I.V.E.K"],
      ["3:15 AM", "CHMURA B2B SATURNA"],
      ["4:45 AM", "ATYYA"]
    ],
    "living-room": [
      ["1:00 PM", "ROSSO"],
      ["2:00 PM", "DUBCONSCIOUS"],
      ["3:00 PM", "GLoBAL"],
      ["4:00 PM", "ROB PAINE"],
      ["6:00 PM", "SOOHAN"],
      ["7:30 PM", "STAVROZ"],
      ["9:00 PM", "ADHAM SHAIKH"],
      ["10:30 PM", "MUNGO'S HI FI"],
      ["12:00 AM", "UNCLE WAFFLES"],
      ["1:00 AM", "AMÉMÉ"],
      ["3:00 AM", "THOMAS WORKSHOP"]
    ],
    "pagoda": [
      ["4:00 PM", "DJ JUST-B"],
      ["5:00 PM", "TKO"],
      ["6:00 PM", "DOUBLE TROUBLE"],
      ["7:00 PM", "ARMONIA"],
      ["8:00 PM", "STRESSHEAD"],
      ["9:00 PM", "ATRIP"],
      ["10:00 PM", "LAVERN"],
      ["11:00 PM", "BORIS BREJCHA"],
      ["12:30 AM", "ELI BROWN"],
      ["1:45 AM", "THE DARE DJ SET"],
      ["3:00 AM", "TWO SHELL"],
      ["4:00 AM", "BRUNELLO"]
    ],
    "village": [
      ["6:00 PM", "SKRADLEY"],
      ["7:00 PM", "KINDLL"],
      ["8:30 PM", "ILL.GATES"],
      ["9:30 PM", "JUSTIN HAWKES"],
      ["10:30 PM", "LEVEL UP"],
      ["11:30 PM", "SEVEN LIONS"],
      ["12:30 AM", "DIMENSION"],
      ["1:30 AM", "SIGMA"],
      ["2:30 AM", "PHIBES"],
      ["3:30 AM", "THE CHILLAGE HOSTED BY ILL.GATES"]
    ]
  },
  "Sunday": {
    "amp": [
      ["4:30 PM", "SUNDAY AFTERNOON SALOON W/ MARIN PATENAUDE"],
      ["6:30 PM", "ORENDA"],
      ["7:30 PM", "SNUFFY"],
      ["8:30 PM", "SHOSH"],
      ["9:30 PM", "VILLAGER"],
      ["10:30 PM", "TAIKI NULIGHT"],
      ["12:00 AM", "HAMDI"],
      ["1:30 AM", "BADGER"],
      ["3:00 AM", "BL3SS"]
    ],
    "fractal-forest": [
      ["1:00 PM", "FRACTAL FUNK JAM HOSTED BY SMALLTOWN DJS"],
      ["5:00 PM", "Z-TRIP"],
      ["6:00 PM", "BROTHERS MACKLOVITCH"],
      ["7:00 PM", "PINEO & LOEB FT. DRAGONETTE"],
      ["8:00 PM", "SKIITOUR"],
      ["9:00 PM", "THE SPONGES"],
      ["10:00 PM", "JUSTIN JAY"],
      ["11:00 PM", "MATRODA"],
      ["12:00 AM", "CLOONEE"],
      ["1:00 AM", "WESTEND"],
      ["2:00 AM", "DJ SUSAN"],
      ["3:00 AM", "RUMPUS"],
      ["4:00 AM", "THOMAS ANTHONY"],
      ["5:00 AM", "WES PLEASE"],
      ["6:30 AM", "JUSTIN HALE"],
      ["8:00 AM", "RICH-E-RICH"]
    ],
    "grove": [
      ["5:00 PM", "SHUKA"],
      ["6:00 PM", "GABBY HAZE"],
      ["7:00 PM", "VIRAVIRA"],
      ["8:00 PM", "KAYA KO"],
      ["9:00 PM", "EVA LAZARUS"],
      ["10:00 PM", "CIRCUS ACTS INSOMNIACS"],
      ["10:15 PM", "DRAMA DJ SET"],
      ["11:30 PM", "TYCHO DJ SET"],
      ["1:00 AM", "JACQUES GREENE"],
      ["2:30 AM", "CAMEO BLUSH"],
      ["4:00 AM", "PLAYER DAVE"],
      ["5:30 AM", "FRAMEWORKS"]
    ],
    "living-room": [
      ["12:00 PM", "MARTY CARTER"],
      ["1:00 PM", "SIJAY JAMES"],
      ["2:00 PM", "K-TEL"],
      ["3:00 PM", "BREAKFLUID"],
      ["4:00 PM", "NATASCHA POLKÉ"],
      ["5:30 PM", "CIVILLIAN"],
      ["6:45 PM", "TONE RANGER"],
      ["8:15 PM", "INTERMISSION DJ"],
      ["8:30 PM", "MAT THE ALIEN & MAGUGU"],
      ["9:30 PM", "KOJI AIKEN"],
      ["10:30 PM", "MACHINEDRUM"],
      ["11:30 PM", "SAM BINGA"],
      ["12:30 AM", "JOSH WINK"],
      ["2:00 AM", "ALEX OXLEY"],
      ["3:30 AM", "ROXANNE ROLL"],
      ["5:00 AM", "MICHAEL RED"],
      ["7:00 AM", "LION S"]
    ],
    "pagoda": [
      ["4:00 PM", "BE HAZZY"],
      ["5:00 PM", "AVYON"],
      ["6:00 PM", "CHIMP IT"],
      ["7:00 PM", "ASHEZ"],
      ["8:00 PM", "SHIMA"],
      ["9:00 PM", "LYNY"],
      ["10:00 PM", "ZINGARA"],
      ["11:00 PM", "CLOZEE"],
      ["12:15 AM", "KAI WACHI"],
      ["1:30 AM", "BLACK TIGER SEX MACHINE"],
      ["2:45 AM", "NITEPUNK"],
      ["4:00 AM", "SIPPY"],
      ["5:00 AM", "DOWNLO"]
    ],
    "village": [
      ["5:00 PM", "DNB GIRLS TAKEOVER HOSTED BY CRYSTAL FRESH"],
      ["8:00 PM", "DLB"],
      ["9:00 PM", "TRIPLE XL"],
      ["10:00 PM", "IVYJ"],
      ["11:00 PM", "P MONEY & WHINEY"],
      ["12:30 AM", "GANJA WHITE NIGHT"],
      ["1:45 AM", "CRANKDAT"],
      ["3:00 AM", "VIPERACTIVE"],
      ["4:00 AM", "THA FUNK JUNKIE W/ PAV4N"]
    ]
  }
};
